### PR TITLE
Increase the size of the assembly. 

### PR DESCRIPTION
**Pull request by SilasK**
Hey @brwnj 
As discussed by mail, If Atlas is used to create functional and taxonomic table of the whole microbiome  we should increase the size of the assembly. (more important than the size of the contigs would be the fraction of reads mapping to it) 

You suggested: 

- [x] shorten the contig cutoffs to ensure maximum output from the assembler
- [x] still allow for contig qc but relax defaults
- [x] attempt to annotate joined reads that do not map to contigs

I've drastically decreased the min contigs length required, so that even paired reads are counted as contigs. what do you think? should we still do trimming?

If we want to implement your third point we need to merge the reads that don't map the contigs. Why not doing a second assembly with all not-normalised reads not mapping to the contigs ?

### CODE REVIEW

**Comment by SilasK** [comment]
I resolved an other problem which might interfere with the contig filtering, see the commit messages

**Comment by SilasK** [comment]
`expand("{{sample}}/assembly/unmapped_post_filter/{{sample}}_unmapped.merged_{fraction}.fastq.gz",
                          fraction=MULTIFILE_FRACTIONS)`

**Comment by SilasK** [comment]
I will test the results on the cami data.

**Comment by SilasK** [comment]
Impressive increase of assembly size thanks to better merging and less filtering. 


  | n_scaffolds | n_contigs | contig_bp | scaf_N50 | scaf_L50 | ctg_N50 | ctg_L50 | ctg_N90 | ctg_L90 | ctg_max
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
default | 30'976.00 | 30'976.00 | 233'146'685.00 | 3'787.00 | 11'265.00 | 3'787.00 | 11'265.00 | 21'767.00 | 2'945.00 | 814'148.00
increased_assembly | 451'194.00 | 451'194.00 | 500'632'152.00 | 40'667.00 | 1'922.00 | 40'667.00 | 1'922.00 | 303'286.00 | 421.00 | 987'198.00

**Comment by brwnj** [comment]
We need to `outu` to capture unmapped reads from rule `align_reads_to_final_contigs`. I'm curious if it's mostly single-end or paired reads that do not map and then we can start to characterize why for this sample.

**Comment by SilasK** [comment]
outu is done by default. 

From the log file paired end reads aligned ~50% and singletons 45%. But there are far more paired end reads. We map the unnormalized QC reads which are not merged. 

[prefiltered_contig_coverage_stats.log](https://github.com/pnnl/atlas/files/1839231/prefiltered_contig_coverage_stats.log)

**Pull request closed without merging**
