### PR TITLE
Binner

### PR DESCRIPTION
**Pull request by SilasK**
Updated binning capability: metabat, concoct, maxbin

For now only maxbin is passed trough checkm, but it is possible to generate bin reports for all three binners or to combine them with e.g. DAS_tool. 

Note: the binner are applied on the filtered contigs of *each* sample, so they don't harness the power to use co-abundance-patterns, for which a co-assembly is required. 

Todo:
- [x] generalize checkm for all binners
- [ ] get read_length param for checkm from redlength log.
- [ ] DAS tool combine and improve bins
- [ ] cross-sample assembly, for concoct and maxbin

If you want test it:

```

# download binning branch

cd path/to/atlas
git checkout binner

# run
snakemake -s path to atlas/atlas/Snakefile --configfile path/your_config_file --config workflow=binning

```

### CODE REVIEW

**Comment by SilasK** [comment]
@sofie8 have a look.

**Comment by Sofie8** [comment]
Ooh amazing news!! I am going to try it, my previous run is still going, but I am going to try the new implementation. Do I run this with snakemake 4.7 or it's the 5 version?

**Comment by SilasK** [comment]
Snakemake v5

**Comment by SilasK** [comment]
@Sofie8  

- a rule which generates the fasta for each bin from the cluster_attribution file. 
- a rule which generates the maxbin/cluster_Attribution.tsv from the bin fastas (annoying that they don't have this option)
- all binners can be run trough checkm
- genes are predicted using prodigal (which can be used for the DAS tool)

download the new update:

```
cd path/atlas 
#if not on binner branch
git checkout binner 

git pull

# run
snakemake -s path/atlas/atlas/Snakefile --configfile path/config.yaml --config workflo="binning"
```

This branch is under active development, it might be that not all commands, e.g. atlas assemble are not working.

**Comment by SilasK** [comment]
@Sofie8 From my first experience I get awful bins with concoct and metabat, virtually none with >90% complete <5% contamination.  I don't think that DAS Tool could improve the nice maxbin bins by combining them with metabat and concoct binning.

**Comment by SilasK** [comment]
I got the DAS tool to work, and it successfully _reduced_ the quality of my bins. 
[F32_DASTool_hqBins.pdf](https://github.com/pnnl/atlas/files/2245149/F32_DASTool_hqBins.pdf)

**Comment by brwnj** [comment]
Such a glowing review!

**Comment by SilasK** [comment]
@Sofie8 

How to add groups to config file for binning:

```
  FR3:
    fastq:
    - /home/kiesers/Metagenomics/Data/CE/FR3_R1.fastq.gz
    - /home/kiesers/Metagenomics/Data/CE/FR3_R2.fastq.gz
    type: metagenomic
    group: R3"
  FR6:
    fastq:
    - /home/kiesers/Metagenomics/Data/CE/FR6_R1.fastq.gz
    - /home/kiesers/Metagenomics/Data/CE/FR6_R2.fastq.gz
    type: metagenomic
    group: "R3"

```

maxbin2 can also handle multiple samples, but for me it didn't produce better results, therefore I removed this oppition.  the groups are however used for concoct and metabat.

**Comment by SilasK** [comment]
I'm workin on the issue with the DAS_Tool, in theory it should work. 

https://github.com/cmks/DAS_Tool/issues/26

**Comment by SilasK** [comment]
@Sofie8 I added the dRep. You can pull the branch and test it.

check out the new parameter, (you can copy paste it in your config):

```
########################
# Binning
########################

final_binner: DASTool             # [DASTool or one of the binner, e.g. maxbin]

binner:                           # If DASTool is used as final_binner, use predictions of this binners
  - metabat
  - concoct
  - maxbin


metabat:
  sensitivity: sensitive
  min_contig_length: 1500 # metabat needs >1500

concoct:
  Nexpected_clusters: 200           # important parameter
  read_length: 100                  # change this parameter !
  Niterations: 500
  min_contig_length: 1000

maxbin:
  max_iteration: 50
  prob_threshold: 0.9
  min_contig_length: 1000

DASTool:
  search_engine: 'diamond'
  score_threshold: 0.5              #Score threshold until selection algorithm will keep selecting bins [0..1].

genome_dereplication:
  ANI: 0.99
  overlap: 0.6
  opt_parameters: ""
  filter:
      noFilter: false
      length: 5000
      completeness: 75
      contamination: 15
  score:
      completeness: 1
      contamination: 5
      N50: 0.5
      length: 0


``

**Pull request merged**
