### PR TITLE
assembly report

### PR DESCRIPTION
**Pull request by SilasK**
Have a look:
[Assembly report](http://htmlpreview.github.com/?https://github.com/pnnl/atlas/blob/report2/docs/reports/assembly_report.html)

[Bin report](http://htmlpreview.github.com/?https://github.com/pnnl/atlas/blob/report2/docs/reports/bin_report.html)

I added a rule to the annotate.snakefile adapted the filenames but didn't liked it to the Snakefile because I can't test it easily.

### CODE REVIEW

**Comment by brwnj** [comment]
I can't get to a point where I can successfully test these. Something is not configured properly for plotly within the environment. My commits mess with styling that is untested, so beware.

**Comment by SilasK** [comment]
I now get errors in the report function. The script can't load snakemeke.utils.report but I don't know why?

**Comment by brwnj** [comment]
That's due to my changes, converting the run block to a shell command. They need to be added as command line arguments and the reports need to be reconfigured to accommodate and be more readable -- mostly to ease maintenance.

**Comment by brwnj** [comment]
This is closer to what I'm hoping for the report scripts:
https://htmlpreview.github.io/?https://github.com/pnnl/atlas/blob/report2/example_data/assemble_logs/report.html

**Comment by brwnj** [comment]
I hope to get to the qc report before the week ends then I'll get these tested via snakemake execution.

**Comment by SilasK** [comment]
Thank you for greatly improving my dirty scripts.
But I don't see the reason why you want to use the scripts in a `shell`-derective instead of the snakemake [script-direktive](http://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#external-scripts).

**Comment by brwnj** [comment]
To ensure the code always runs within the conda environment. See:

https://bitbucket.org/snakemake/snakemake/src/c98fb24f50f4da41ad4c6fa393711df993a2377a/snakemake/script.py?at=master&fileviewer=file-view-default#script.py-266

And it's easier to debug when dealing with expected arguments.

**Comment by SilasK** [comment]
I take the values directly from the log file from pileup (bbtools). Apparently, this tool doesn't calculate the number of mapped reads correctly. I've mentioned the same problem in #105. Probably, pileup has a problem counting the reads from the sam file with paired and unpaired reads.

**Comment by SilasK** [comment]
I think I will have to find an other way to calculate the number of mapped reads. I keep you updated.

**Comment by SilasK** [comment]
Hi @Sofie8,

First of all yes the QC reads are mapped to the contigs.
If you have raw  paired-end reads Atlas keeps singletons, whose mate was
fiétered out. The QC reads contain therefore Paired + singletons.

Apparently bbmap tools have difficulties to handle this. I don't know what
is the best way to gandle sam files with paired and single end reads. Any
Ideas?

In the log file of the paired end are counted double. So this high number
makes sense.

In the last version I removed the option for physical coverage calculation.
The results is that the mapping rates are closer to what I expect and the
coverage is no more negative.

**Comment by Sofie8** [comment]
Hi Silas,

I ran the new version (1.0.33) and indeed the numbers of reads and mapped reads look fine now in the pilup_final_contigs.log!

Reads:                               	3011216
Mapped reads:                        2919032
Mapped bases:                        635213637
Ref scaffolds:                       	17936
Ref bases:                           	22709205

So I think it is solved. Thank you!

**Pull request merged**
