### PR TITLE
Create combine_contigs.smk

### PR DESCRIPTION
**Pull request by SilasK**

### CODE REVIEW

**Comment by SilasK** [comment]
@brwnj What do you think of my solution to combine contigs?

This increases recovery of contigs from samples and should to construct large MAGs, which are still of high quality. It should be better than just do a co-assembly of all reads.

In addition it should allow to compare MAGs from different samples #87 
Instead of calling Prokka on each sample one could call it on each genome. 

If there are stain differences between samples, they should be identified afterwards by bined coverage.

**Comment by brwnj** [comment]
I like this idea. Is this accurate:

+ merge contigs
+ align reads to contigs for coverage and bam
+ create bins (MAGs)

My recommendation would be that we then merge compatible bins:

https://www.nature.com/articles/s41564-017-0012-7#Sec10

Then we need to figure out what's necessary to link contig, loci, coverage across loci, and bin + bin QC data.

**Comment by SilasK** [comment]
To do:
- [x] merge contigs
- [x] map reads to contigs
- [x] create MAGs with concoct for low complexity samples
- [ ] metBAT for high complexity 
- [ ] merge bins with check_m
- [ ] call genes with prokka for each genome
- [ ] quantify abundance of MAG and genes in each sample
- [ ] combine abundance tables
- [x] store bam
- [ ] visualise with Anvi'o

**Comment by SilasK** [comment]
@brwnj How should I integrate this part into Atlas.

replacing the annotation workflow, 
Alternative workflow with command
Do you want to continue to call MAGs specific to each sample?

**Comment by SilasK** [comment]
@brwnj Any comments on this branch?

**Comment by brwnj** [comment]
Thanks for being patient on this one. I'll try to fully review soon.

**Comment by brwnj** [comment]
Is this something we're hoping to add to the publication? I'm hoping to finish that soon and submit and this branch feels like it will need significant testing.

**Comment by SilasK** [comment]
@brwnj  what do you think of combining bins with dREP ?https://www.nature.com/articles/ismej2017126

**Pull request closed without merging**
