### PR TITLE
Assembly

### PR DESCRIPTION
**Pull request by SilasK**
I'm sorry there where still some bugs in #40 I corrected them here and tested them on paired and single end dummy data. I pushed them directly to the master to resolve the bugs. 

Now we have:

 -trimming
 - decontamination
 - deduplication (optional)

QC reads:

preprocessing assembly:
 - normalization
 - errorcorr
 - merging

order can be changed via the list in the config file.

However the QC reads are maped to the contigs, which alow also vairant calling. 

@brwnj  what do you think of that?

### CODE REVIEW

**Comment by brwnj** [comment]
Thanks for getting that updated! I bumped the version and will create a new release.

**Comment by SilasK** [comment]
@brwnj  For the new release:
need to add `click` as prerequisite.

then it would be possible to do a bioconda recipie?

**Comment by brwnj** [comment]
I can't get local tests working on this at the moment, but here's a start:
https://github.com/bioconda/bioconda-recipes/tree/adds-pnnl-atlas

**Comment by camel315** [comment]
Dear Silask, 
With the latest atlas (v 1.0.19), it appears an error in the beginning of the running like blow:
image
Could you please have a look and fix it up?
Thank you.

**Comment by camel315** [comment]
@SilasK Sorry to disturb you. I have a problem when running atlas at initialize_checkm like below:
(The --latency-wait has been set to 20 sec).
localrule initialize_checkm:
    output: /panfs/panfs14.gfz-hpcc.cluster/home/gmb/syang/databases/checkm/test_data/637000110.fna, /panfs/panfs14.gfz-hpcc.cluster/home/gmb/syang/databases/checkm/taxon_marker_sets.tsv, ....
Conda environment defines Python version < 3.3. Using Python of the master process to execute script.
/home/syang/anaconda3/bin/python /home/syang/anaconda3/lib/python3.6/site-packages/atlas/rules/.snakemake.35yfhhjg.initialize_checkm.py

*******************************************************************************
 [CheckM - data] Check for database updates. [setRoot]
*******************************************************************************

Data location successfully changed to: /panfs/panfs14.gfz-hpcc.cluster/home/gmb/syang/databases/checkm

*******************************************************************************
 [CheckM - data] Check for database updates. [update]
*******************************************************************************

Waiting at most 20 seconds for missing files.
Error in job initialize_checkm while creating output files /panfs/panfs14.gfz-hpcc.cluster/home/gmb/syang/databases/c ...
MissingOutputException in line 941 of /home/syang/anaconda3/lib/python3.6/site-packages/atlas/rules/assemble.snakefile:
Missing files after 20 seconds:
...
Removing output files of failed job initialize_checkm since they might be corrupted:
/panfs/panfs14.gfz-hpcc.cluster/home/gmb/syang/databases/checkm/.dmanifest, logs/checkm_init.txt
Will exit after finishing currently running jobs.

**Pull request merged**
